FROM node:24-alpine3.20 AS base

ARG http_proxy
ARG https_proxy
ENV http_proxy=${http_proxy}
ENV https_proxy=${https_proxy}

RUN corepack enable && corepack prepare pnpm@9.15.9 --activate

WORKDIR /opt/app

# Install dependencies

COPY frontend/package.json ./
COPY frontend/pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY frontend/ ./

CMD ["pnpm", "dev"]